-- MySQL Script generated by MySQL Workbench
-- Wed Feb 16 10:04:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dr_dumbledore_army_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dr_dumbledore_army_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dr_dumbledore_army_blog` DEFAULT CHARACTER SET utf8 ;
USE `dr_dumbledore_army_blog` ;

-- -----------------------------------------------------
-- Table `dr_dumbledore_army_blog`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dr_dumbledore_army_blog`.`tb_user` (
  `id` BIGINT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name_user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `photo` VARCHAR(255) NULL,
  `date_birth` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dr_dumbledore_army_blog`.`tb_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dr_dumbledore_army_blog`.`tb_theme` (
  `id` BIGINT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dr_dumbledore_army_blog`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dr_dumbledore_army_blog`.`post` (
  `id` BIGINT NOT NULL,
  `title` TEXT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `photo` VARCHAR(255) NULL,
  `tb_user_id` BIGINT NOT NULL,
  `tb_theme_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_tb_user_idx` (`tb_user_id` ASC) VISIBLE,
  INDEX `fk_post_tb_theme1_idx` (`tb_theme_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_tb_user`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `dr_dumbledore_army_blog`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_tb_theme1`
    FOREIGN KEY (`tb_theme_id`)
    REFERENCES `dr_dumbledore_army_blog`.`tb_theme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
